// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharmacy.Models
{
    [Table("catalog")]
    public partial class catalog
    {
        public catalog()
        {
            medicines = new HashSet<medicine>();
        }

        [Key]
        public int cat_id { get; set; }
        [StringLength(50)]
        public string cat_name { get; set; }
        [StringLength(100)]
        public string cat_desc { get; set; }

        [InverseProperty("cat")]
        public virtual ICollection<medicine> medicines { get; set; }
    }
}