// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharmacy.Models
{
    [Table("comment")]
    public partial class comment
    {
        [Key]
        public int com_id { get; set; }
        public string com_desc { get; set; }
        public int? user_id { get; set; }
        public int? med_id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? time { get; set; }

        [ForeignKey("med_id")]
        [InverseProperty("comments")]
        public virtual medicine med { get; set; }
        [ForeignKey("user_id")]
        [InverseProperty("comments")]
        public virtual user user { get; set; }
    }
}