// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharmacy.Models
{
    [Table("order")]
    public partial class order
    {
        [Key]
        public int ord_id { get; set; }
        public int? ord_quantity { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ord_time { get; set; }
        public int? user_id { get; set; }
        public int? med_id { get; set; }

        [ForeignKey("med_id")]
        [InverseProperty("orders")]
        public virtual medicine med { get; set; }
        [ForeignKey("user_id")]
        [InverseProperty("orders")]
        public virtual user user { get; set; }
    }
}