// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace pharmacy.Models
{
    [Table("user")]
    public partial class user
    {
        public user()
        {
            comments = new HashSet<comment>();
            medicines = new HashSet<medicine>();
            orders = new HashSet<order>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]

        [Required(ErrorMessage = "please enter Name")]
        [MinLength(3, ErrorMessage = "at least 3 char")]

        public string name { get; set; }
        [StringLength(100)]

        [Required(ErrorMessage = "please enter Email")]
        [EmailAddress(ErrorMessage = "invalid Email")]

        public string email { get; set; }
        [StringLength(50)]

        [Required(ErrorMessage = "please enter Password")]

        public string password { get; set; }
        [StringLength(200)]


        [NotMapped]
        [Required(ErrorMessage = "please enter Confirm Password")]
        [Compare("password", ErrorMessage = "password not match")]
        public string confirm_password { get; set; }
        [StringLength(200)]

        [Required(ErrorMessage = "please enter Address")]
        public string adderss { get; set; }
        [Phone(ErrorMessage = "this phone number is not correct")]
        [Required(ErrorMessage = "please enter phone")]
        public int? phone { get; set; }
        [Column(TypeName = "date")]

        [Required(ErrorMessage = "please choose your Birthdate")]

        public DateTime? birthdate { get; set; }
        [StringLength(10)]


        [Required(ErrorMessage = "please Enter your Tybe")]

        public string sex { get; set; }
        [StringLength(100)]

        [Required(ErrorMessage = "please upload your image")]
        public string img { get; set; }

        [InverseProperty("user")]
        public virtual ICollection<comment> comments { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<medicine> medicines { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<order> orders { get; set; }
    }
}